<x-layouts::app :title="__('admin.feature_catalog.title')">
    @php
        $sortable = __('admin.feature_catalog.sortable');
        $sortUrl = fn (string $column) => route('admin.features.index', array_merge(request()->except(['sort', 'direction', 'page']), ['sort' => $column, 'direction' => $sort === $column && $direction === 'asc' ? 'desc' : 'asc']));
        $marker = fn (string $column) => $sort === $column ? ($direction === 'asc' ? ' ↑' : ' ↓') : '';
        $valueTypes = __('admin.feature_catalog.value_types');
        $detailTypes = __('admin.feature_catalog.detail_types');
    @endphp

    <div class="space-y-6">
        <div class="flex flex-wrap items-start justify-between gap-3"><div><flux:heading size="xl">{{ __('admin.feature_catalog.title') }}</flux:heading><flux:text class="mt-1">{{ __('admin.feature_catalog.intro') }}</flux:text></div><a href="{{ route('admin.index') }}" class="rounded-lg border border-zinc-300 px-3 py-2 text-sm dark:border-zinc-700">{{ __('admin.feature_catalog.back_admin') }}</a></div>
<div class="flex gap-2 border-b border-zinc-200 dark:border-zinc-800"><a href="{{ route('admin.features.index') }}" @class(['border-b-2 px-3 py-2 text-sm font-semibold', 'border-amber-500' => $section === 'features', 'border-transparent text-zinc-500' => $section !== 'features'])>{{ __('admin.feature_catalog.features') }}</a><a href="{{ route('admin.features.index', ['section' => 'categories']) }}" @class(['border-b-2 px-3 py-2 text-sm font-semibold', 'border-amber-500' => $section === 'categories', 'border-transparent text-zinc-500' => $section !== 'categories'])>{{ __('admin.feature_catalog.categories') }}</a></div>

        @if($section === 'features')
            <details class="rounded-xl border border-amber-300 bg-amber-50/50 p-4 dark:border-amber-800 dark:bg-amber-950/20" @if($errors->any() && old('slug')) open @endif><summary class="cursor-pointer font-semibold">+ {{ __('admin.feature_catalog.add_feature') }}</summary><div class="mt-4">@include('admin.features._form', ['feature' => null, 'action' => route('admin.features.store'), 'method' => 'POST'])</div></details>

            <form method="GET" class="grid gap-3 rounded-xl border border-zinc-200 p-4 md:grid-cols-5 dark:border-zinc-800">
                <input name="search" value="{{ $filters['search'] }}" placeholder="{{ __('admin.feature_catalog.search_placeholder') }}" class="rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-950">
                <select name="category" class="rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-950"><option value="">{{ __('admin.feature_catalog.all_categories') }}</option>@foreach($categories as $category)<option value="{{ $category->slug }}" @selected($filters['category'] === $category->slug)>{{ $category->name_localized ?: $category->name_fallback ?: $category->slug }}</option>@endforeach</select>
                <select name="place_type" class="rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-950"><option value="">{{ __('admin.feature_catalog.all_place_types') }}</option>@foreach($placeTypes as $placeType)<option value="{{ $placeType->slug }}" @selected($filters['place_type'] === $placeType->slug)>{{ $placeType->name_localized ?: $placeType->name_fallback ?: $placeType->slug }}</option>@endforeach</select>
                <select name="activity" class="rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-950"><option value="all">{{ __('admin.feature_catalog.activity_all') }}</option><option value="active" @selected($filters['activity'] === 'active')>{{ __('admin.feature_catalog.activity_active') }}</option><option value="inactive" @selected($filters['activity'] === 'inactive')>{{ __('admin.feature_catalog.activity_inactive') }}</option></select>
                <button class="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-zinc-950">{{ __('admin.feature_catalog.filter') }}</button>
                <input type="hidden" name="sort" value="{{ $sort }}"><input type="hidden" name="direction" value="{{ $direction }}">
            </form>

            <div class="overflow-x-auto rounded-xl border border-zinc-200 dark:border-zinc-800"><table class="min-w-[1200px] w-full divide-y divide-zinc-200 text-left text-sm dark:divide-zinc-800"><thead class="bg-zinc-50 text-xs text-zinc-500 dark:bg-zinc-900"><tr>@foreach($sortable as $column => $label)<th class="px-3 py-3"><a href="{{ $sortUrl($column) }}">{{ $label }}{{ $marker($column) }}</a></th>@endforeach<th class="px-3 py-3">{{ __('admin.feature_catalog.options_details') }}</th><th class="px-3 py-3">{{ __('admin.feature_catalog.action') }}</th></tr></thead><tbody class="divide-y divide-zinc-200 dark:divide-zinc-800">
                @forelse($features as $feature)
                    <tr @class(['opacity-60' => !$feature->is_active])><td class="px-3 py-3"><div class="font-semibold">{{ $feature->name_localized ?: $feature->name_fallback ?: $feature->slug }}</div><div class="text-xs text-zinc-400">{{ app()->getLocale() === 'de' ? $feature->name_en : $feature->name_de }}</div></td><td class="px-3 py-3 font-mono text-xs">{{ $feature->slug }}</td><td class="px-3 py-3">{{ $feature->category_name_localized ?: $feature->category_name_fallback ?: $feature->category_slug }}</td><td class="px-3 py-3">{{ $valueTypes[$feature->value_type] ?? $feature->value_type }}</td><td class="px-3 py-3 text-center">{{ $feature->usage_count }}</td><td class="px-3 py-3">{{ $feature->is_active ? __('admin.feature_catalog.yes') : __('admin.feature_catalog.no') }}</td><td class="px-3 py-3">{{ $feature->is_searchable ? __('admin.feature_catalog.yes') : __('admin.feature_catalog.no') }}</td><td class="px-3 py-3">{{ $feature->sort_order }}</td><td class="px-3 py-3"><div class="text-xs">{{ trans_choice('admin.feature_catalog.status_count', count($feature->workflow['status_options'] ?? []), ['count' => count($feature->workflow['status_options'] ?? [])]) }} · {{ trans_choice('admin.feature_catalog.detail_count', count($feature->workflow['details'] ?? []), ['count' => count($feature->workflow['details'] ?? [])]) }}</div></td><td class="px-3 py-3"><button type="button" data-editor-toggle="feature-editor-{{ $feature->id }}" class="rounded border border-zinc-300 px-2 py-1 text-xs font-semibold dark:border-zinc-700">{{ __('admin.feature_catalog.edit') }}</button></td></tr>
                    <tr id="feature-editor-{{ $feature->id }}" class="hidden bg-zinc-50/60 dark:bg-zinc-900/50"><td colspan="10" class="p-4">@include('admin.features._form', ['feature' => $feature, 'action' => route('admin.features.update', $feature->id), 'method' => 'PUT'])</td></tr>
                @empty<tr><td colspan="10" class="p-8 text-center text-zinc-500">{{ __('admin.feature_catalog.no_features') }}</td></tr>@endforelse
            </tbody></table></div>
            {{ $features->links() }}
        @else
            <details class="rounded-xl border border-amber-300 bg-amber-50/50 p-4 dark:border-amber-800 dark:bg-amber-950/20"><summary class="cursor-pointer font-semibold">+ {{ __('admin.feature_catalog.add_category') }}</summary><form method="POST" action="{{ route('admin.feature-categories.store') }}" class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">@csrf@include('admin.features._category-fields', ['category' => null])<div class="xl:col-span-4 flex justify-end"><button class="rounded bg-zinc-900 px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-zinc-950">{{ __('admin.feature_catalog.add_category') }}</button></div></form></details>
            <div class="space-y-3">@forelse($categories as $category)<details class="rounded-xl border border-zinc-200 p-4 dark:border-zinc-800"><summary class="cursor-pointer"><span class="font-semibold">{{ $category->name_localized ?: $category->name_fallback ?: $category->slug }}</span><span class="ml-2 text-xs text-zinc-400">{{ trans_choice('admin.feature_catalog.feature_count', $category->feature_count, ['count' => $category->feature_count]) }} · {{ $category->is_active ? __('admin.feature_catalog.active_lower') : __('admin.feature_catalog.inactive_lower') }}</span></summary><form method="POST" action="{{ route('admin.feature-categories.update', $category->id) }}" class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">@csrf @method('PUT') @include('admin.features._category-fields', ['category' => $category])<div class="xl:col-span-4 flex justify-end"><button class="rounded bg-zinc-900 px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-zinc-950">{{ __('admin.feature_catalog.save_category') }}</button></div></form></details>@empty<div class="rounded-xl border border-zinc-200 p-6 text-sm text-zinc-500 dark:border-zinc-800">{{ __('admin.feature_catalog.no_categories') }}</div>@endforelse</div>
        @endif
    </div>

    <template id="feature-status-row"><div class="grid gap-2 md:grid-cols-[160px_1fr_1fr_auto]" data-repeat-row><input name="statuses[__INDEX__][value]" required placeholder="{{ __('admin.feature_catalog.value') }}" class="rounded border border-zinc-300 bg-white px-2 py-1.5 font-mono text-xs dark:border-zinc-700 dark:bg-zinc-950"><input name="statuses[__INDEX__][de]" required placeholder="{{ __('admin.feature_catalog.german') }}" class="rounded border border-zinc-300 bg-white px-2 py-1.5 text-sm dark:border-zinc-700 dark:bg-zinc-950"><input name="statuses[__INDEX__][en]" required placeholder="{{ __('admin.feature_catalog.english') }}" class="rounded border border-zinc-300 bg-white px-2 py-1.5 text-sm dark:border-zinc-700 dark:bg-zinc-950"><button type="button" data-remove-row class="rounded border border-red-300 px-2 text-xs text-red-600">{{ __('admin.feature_catalog.remove') }}</button></div></template>
    <template id="feature-detail-row"><div class="rounded-lg border border-zinc-200 p-3 dark:border-zinc-800" data-repeat-row><div class="grid gap-2 md:grid-cols-2 xl:grid-cols-4"><input name="details[__INDEX__][key]" placeholder="{{ __('admin.feature_catalog.technical_key') }}" class="rounded border border-zinc-300 bg-white px-2 py-1.5 font-mono text-xs dark:border-zinc-700 dark:bg-zinc-950"><select name="details[__INDEX__][type]" class="rounded border border-zinc-300 bg-white px-2 py-1.5 text-sm dark:border-zinc-700 dark:bg-zinc-950">@foreach($detailTypes as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select><input name="details[__INDEX__][de]" placeholder="{{ __('admin.feature_catalog.label_de') }}" class="rounded border border-zinc-300 bg-white px-2 py-1.5 text-sm dark:border-zinc-700 dark:bg-zinc-950"><input name="details[__INDEX__][en]" placeholder="{{ __('admin.feature_catalog.label_en') }}" class="rounded border border-zinc-300 bg-white px-2 py-1.5 text-sm dark:border-zinc-700 dark:bg-zinc-950"><input name="details[__INDEX__][unit]" placeholder="{{ __('admin.feature_catalog.unit') }}" class="rounded border border-zinc-300 bg-white px-2 py-1.5 text-sm dark:border-zinc-700 dark:bg-zinc-950"><input name="details[__INDEX__][show_for]" placeholder="{{ __('admin.feature_catalog.visible_for') }}" class="rounded border border-zinc-300 bg-white px-2 py-1.5 text-sm dark:border-zinc-700 dark:bg-zinc-950"><textarea name="details[__INDEX__][options_text]" rows="2" placeholder="{{ __('admin.feature_catalog.options_template_placeholder') }}" class="rounded border border-zinc-300 bg-white px-2 py-1.5 text-xs dark:border-zinc-700 dark:bg-zinc-950 xl:col-span-2"></textarea></div><button type="button" data-remove-row class="mt-2 rounded border border-red-300 px-2 py-1 text-xs text-red-600">{{ __('admin.feature_catalog.remove_detail') }}</button></div></template>

    @push('scripts')<script>(()=>{document.addEventListener('click',(event)=>{const toggle=event.target.closest('[data-editor-toggle]');if(toggle){document.getElementById(toggle.dataset.editorToggle)?.classList.toggle('hidden');return;}const remove=event.target.closest('[data-remove-row]');if(remove){remove.closest('[data-repeat-row]')?.remove();return;}const form=event.target.closest('[data-feature-form]');if(!form)return;let template,list;if(event.target.closest('[data-add-status]')){template=document.getElementById('feature-status-row');list=form.querySelector('[data-status-list]');}else if(event.target.closest('[data-add-detail]')){template=document.getElementById('feature-detail-row');list=form.querySelector('[data-detail-list]');}if(template&&list){const index=Date.now().toString();const html=template.innerHTML.replaceAll('__INDEX__',index);list.insertAdjacentHTML('beforeend',html);}});})();</script>@endpush
</x-layouts::app>
